var shoeList = [
  {
    id: 1,
    category: "Women",
    brand: "Ivonia",
    edition: "Ivonia high heels",
    color: "Red",
    size: 6,
    qty: 5,
    price: 400,
    image_url:
      "https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 2,
    category: "Men",
    brand: "Splendid",
    edition: "Splendid formal shoe",
    color: "Brown",
    size: 7,
    qty: 9,
    price: 500,
    image_url:
      "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    category: "Women",
    brand: "Ivonia",
    edition: "Ivonia 2nd edition heel",
    color: "Red",
    size: 4,
    qty: 15,
    price: 350,
    image_url:
      "https://images.pexels.com/photos/1446524/pexels-photo-1446524.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    category: "Men",
    brand: "Superba",
    edition: "Superba sneaker",
    color: "Black",
    size: 5,
    qty: 11,
    price: 489,
    image_url:
      "https://images.pexels.com/photos/11962271/pexels-photo-11962271.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,
    category: "Women",
    brand: "Cloraine",
    edition: "Cloraine super woman",
    color: "White",
    size: 6,
    qty: 11,
    price: 500,
    image_url:
      "https://images.pexels.com/photos/313707/pexels-photo-313707.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,
    category: "Women",
    brand: "Cloraine",
    edition: "Cloraine 2nd edition",
    color: "White",
    size: 6,
    qty: 16,
    price: 400,
    image_url:
      "https://images.pexels.com/photos/10257094/pexels-photo-10257094.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 7,
    category: "Women",
    brand: "Rivonil",
    edition: "Rivonil heel",
    color: "Orange",
    size: 5,
    qty: 11,
    price: 300,
    image_url:
      "https://images.pexels.com/photos/949590/pexels-photo-949590.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 8,
    category: "Men",
    brand: "Splendid",
    edition: "Splendid 2 formal shoe",
    color: "Brown",
    size: 8,
    qty: 11,
    price: 300,
    image_url:
      "https://images.pexels.com/photos/2989593/pexels-photo-2989593.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 9,
    category: "Men",
    brand: "Kulca",
    edition: "Kulca tekkies",
    color: "White",
    size: 9,
    qty: 20,
    price: 250,
    image_url:
      "https://images.pexels.com/photos/4429559/pexels-photo-4429559.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 10,
    category: "Women",
    brand: "Superba",
    edition: "Superba trainers",
    color: "Grey",
    size: 7,
    qty: 10,
    price: 300,
    image_url:
      "https://images.pexels.com/photos/1750045/pexels-photo-1750045.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 11,
    category: "Kids",
    brand: "Baby json",
    edition: "Baby Json sneakers",
    color: "Blue",
    size: 3,
    qty: 25,
    price: 299,
    image_url:
      "https://images.pexels.com/photos/4987516/pexels-photo-4987516.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 12,
    category: "Kids",
    brand: "Baby json",
    edition: "Baby Json shoes",
    color: "Blue",
    size: 2,
    qty: 10,
    price: 199,
    image_url:
      "https://images.pexels.com/photos/8216701/pexels-photo-8216701.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 13,
    category: "Kids",
    brand: "Rainbow",
    edition: "Rainbow kids sneakers",
    color: "Mixed",
    size: 4,
    qty: 10,
    price: 300,
    image_url:
      "https://images.pexels.com/photos/6182563/pexels-photo-6182563.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 14,
    category: "Kids",
    brand: "Rainbow",
    edition: "Rainbow 2 kids sneakers",
    color: "Black",
    size: 3,
    qty: 12,
    price: 300,
    image_url:
      "https://images.pexels.com/photos/12955703/pexels-photo-12955703.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 15,
    category: "kids",
    brand: "Baby json",
    edition: "Baby json sliders",
    color: "Pink",
    size: 3,
    qty: 14,
    price: 200,
    image_url:
      "https://images.pexels.com/photos/8801134/pexels-photo-8801134.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 16,
    category: "Men",
    brand: "Mike",
    edition: "Mike trainers",
    color: "Orange",
    size: 7,
    qty: 12,
    price: 400,
    image_url:
      "https://images.pexels.com/photos/4997003/pexels-photo-4997003.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 17,
    category: "All",
    brand: "Tronies",
    edition: "Tronies flexies",
    color: "Blue",
    size: 7,
    qty: 18,
    price: 250,
    image_url:
      "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 18,
    category: "Kids",
    brand: "Baby json",
    edition: "Baby json wear",
    color: "Black and white",
    size: 2,
    qty: 18,
    price: 100,
    image_url:
      "https://images.pexels.com/photos/267278/pexels-photo-267278.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 19,
    category: "Men",
    brand: "Tronies",
    edition: "Tronies flexies chillas",
    color: "Black and white",
    size: 9,
    qty: 18,
    price: 300,
    image_url:
      "https://images.pexels.com/photos/1122605/pexels-photo-1122605.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 20,
    category: "Women",
    brand: "Ivonia",
    edition: "Ivonia high heels 2",
    color: "Black",
    size: 6,
    qty: 18,
    price: 400,
    image_url:
      "https://images.pexels.com/photos/1161730/pexels-photo-1161730.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 21,
    category: "Kids",
    brand: "Baby json",
    edition: "Baby json wear 2",
    color: "Green",
    size: 3,
    qty: 18,
    price: 300,
    image_url:
      "https://images.pexels.com/photos/47220/shoes-pregnancy-child-clothing-47220.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];
